# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
terraform_backend_defaults:
  type: gcs
  configuration:
    bucket: gcp64-03-2026-terraform

vars:
  deployment_name: gcp64-03-2026
  project_id: projectseald
  region: us-south1
  zone: us-south1-b"
  # a3u_reservation_name: ["futres-20260305-003107-2vm-a","futres-20260305-003107-1vm-b","futres-20260305-003107-1vm-c","futres-20260305-003107-1vm-d","futres-20260305-003107-1vm-e","futres-20260305-003107-1vm-f","futres-20260305-003107-1vm-g","futres-20260305-003107-1vm-h"]
  a3u_cluster_size: 7
  a3ultra_node_a_size: 2
  a3ultra_node_c_size: 1
  a3ultra_node_d_size: 1
  a3ultra_node_e_size: 1
  a3ultra_node_f_size: 1
  a3ultra_node_g_size: 1

# Additional provisioning models (pick only one), can be used to substitute `a3u_reservation_name`:
#
# a3u_dws_flex_enabled: true
#
# To make use of DWS Flex-Start, for more info visit: https://github.com/GoogleCloudPlatform/cluster-toolkit/blob/main/docs/slurm-dws-flex.md
#
# a3u_enable_spot_vm: true
#
# To make use of Spot VMs, for more info visit: https://cloud.google.com/compute/docs/instances/spot
